### ISSUE TITLE
Add Tests

### ISSUE THREAD

**Issue by e1Ru1o** [2kodevs/Azul-Game#8]
**Is your feature request related to a problem? Please describe.**
Nothing related to #1 and #6 are tested.

**Describe the solution you'd like**
Write a test suit for each method in game.pl, and the non trivial ones of utils.pl

**Comment by stdevRulo** [comment]
@stdevRulo aqui me confundi ya lo arregle, quice decir untested

**Comment by e1Ru1o** [comment]
Changes in #9 affect the behavior of some methods. Merge is recommended
